-- take assets from qx service including id for easier initial data import
INSERT INTO assets (id, issuer, name) VALUES (1, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'QX');
INSERT INTO assets (id, issuer, name) VALUES (2, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'RANDOM');
INSERT INTO assets (id, issuer, name) VALUES (3, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'QUTIL');
INSERT INTO assets (id, issuer, name) VALUES (4, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'QTRY');
INSERT INTO assets (id, issuer, name) VALUES (5, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'MLM');
INSERT INTO assets (id, issuer, name) VALUES (6, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'QPOOL');
INSERT INTO assets (id, issuer, name) VALUES (7, 'TFUYVBXYIYBVTEMJHAJGEJOOZHJBQFVQLTBBKMEHPEVIZFXZRPEYFUWGTIWG', 'QFT');
INSERT INTO assets (id, issuer, name) VALUES (8, 'CFBMEMZOIDEXQAUXYYSZIURADQLAPWPMNJXQSNVQZAHYVOPYUKKJBJUCTVJL', 'CFB');
INSERT INTO assets (id, issuer, name) VALUES (9, 'QWALLETSGQVAGBHUCVVXWZXMBKQBPQQSHRYKZGEJWFVNUFCEDDPRMKTAUVHA', 'QWALLET');
INSERT INTO assets (id, issuer, name) VALUES (10, 'QCAPWMYRSHLBJHSTTZQVCIBARVOASKDENASAKNOBRGPFWWKRCUVUAXYEZVOG', 'QCAP');
INSERT INTO assets (id, issuer, name) VALUES (11, 'VALISTURNWYFQAMVLAKJVOKJQKKBXZZFEASEYCAGNCFMZARJEMMFSESEFOWM', 'VSTB001');
INSERT INTO assets (id, issuer, name) VALUES (12, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'QEARN');
INSERT INTO assets (id, issuer, name) VALUES (13, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB', 'QVAULT');

SELECT setval('assets_id_seq', 13);